name: MCPlugin
main: io.github.coreyg142.MCPlugin.MCPlugin
version: 0.2
author: ThatOneLegion
description: This is a description of this plugin
api-version: 1.16

commands:
  fuck:
    description: A fucking good command
    usage: /fuck
    permission: MCPlugin.fuck